create table USUARIOS (
	ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    APELLIDO VARCHAR(100),
    USUARIO VARCHAR(100),
    EMAIL VARCHAR(100),
    FECHA_NACIMIENTO DATE,
    DOMICILIO VARCHAR(200),
	PAIS VARCHAR(100),
    PASSWORD1 VARCHAR(100),
    PASSWORD2 VARCHAR(100),
    CATEGORIA VARCHAR(20),
    created_at date,
    updated_at date
)